# Generated by Django 5.1 on 2024-08-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                ("unique_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.IntegerField(blank=True, null=True)),
                ("nazev", models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("unique_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.IntegerField()),
                ("obrazek", models.URLField(blank=True, null=True)),
                ("nazev", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("unique_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.IntegerField()),
                ("nazev", models.CharField(blank=True, max_length=256, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("cena", models.FloatField(blank=True, null=True)),
                ("mena", models.CharField(blank=True, max_length=256, null=True)),
                ("published_on", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("unique_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.IntegerField(blank=True, null=True)),
                ("nazev", models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CatalogAttributeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.attribute"
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.catalog"
                    ),
                ),
            ],
            options={"unique_together": {("attribute", "attribute")},},
        ),
        migrations.AddField(
            model_name="catalog",
            name="attributes_ids",
            field=models.ManyToManyField(
                through="api.CatalogAttributeMapping", to="api.attribute"
            ),
        ),
        migrations.CreateModel(
            name="CatalogImageMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.catalog"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.image"
                    ),
                ),
            ],
            options={"unique_together": {("catalog", "image")},},
        ),
        migrations.AddField(
            model_name="catalog",
            name="obrazek_id",
            field=models.ManyToManyField(
                through="api.CatalogImageMapping", to="api.image"
            ),
        ),
        migrations.CreateModel(
            name="CatalogProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.catalog"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
            options={"unique_together": {("catalog", "product")},},
        ),
        migrations.AddField(
            model_name="catalog",
            name="products_ids",
            field=models.ManyToManyField(
                through="api.CatalogProductMapping", to="api.product"
            ),
        ),
        migrations.CreateModel(
            name="ProductAttributes",
            fields=[
                ("unique_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.IntegerField()),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.attribute",
                        to_field="id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductAttributesProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
                (
                    "product_attributes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.productattributes",
                    ),
                ),
            ],
            options={"unique_together": {("product_attributes", "product")},},
        ),
        migrations.AddField(
            model_name="productattributes",
            name="product",
            field=models.ManyToManyField(
                through="api.ProductAttributesProductMapping", to="api.product"
            ),
        ),
        migrations.CreateModel(
            name="ProductImageImageMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.image"
                    ),
                ),
                (
                    "product_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.productimage",
                    ),
                ),
            ],
            options={"unique_together": {("product_image", "image")},},
        ),
        migrations.AddField(
            model_name="productimage",
            name="obrazek_id",
            field=models.ManyToManyField(
                through="api.ProductImageImageMapping", to="api.image"
            ),
        ),
        migrations.CreateModel(
            name="ProductImageProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
                (
                    "product_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.productimage",
                    ),
                ),
            ],
            options={"unique_together": {("product_image", "product")},},
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ManyToManyField(
                through="api.ProductImageProductMapping", to="api.product"
            ),
        ),
    ]
